import type { Metadata } from "next";

import "./globals.css"; // arquivo localizado na pasta SRC

//import "/estilo.css" // arquivo localizado na pasta public

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="cor">
        {children}
      </body>
    </html>
  );
}
